services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: que_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: db

  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    container_name: app

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    container_name: frontend
    depends_on:
      - app

volumes:
  postgres_data:
